//! Phase 2 finalized-intent bridge: verified draft → durable funding intent.
//!
//! Adapted from predecessor paths
//! `crates/gateway/src/stage2_w5h_bridge.rs` at commit
//! `3d30617d1c13231b05e6dd5b072f471b1979eeee` and
//! `crates/gateway/src/runtime/stage2_w5h_intent_finalize_wiring.rs` at
//! commit `ade3d6e942f403bf71960acdf1880bc6a48ccf12`.
//!
//! `draft_id` is a random, non-canonical retry handle. It is generated by
//! `propose_intent`, but proposing never persists it. Only this finalize path
//! writes its consume/tombstone receipt to the bin-owned sidecar. `draft_id`
//! MUST NOT enter either the frozen draft-hash preimage or the canonical
//! `WatchRule`/rule-hash preimage.
//!
//! Persistence deliberately retains the predecessor's non-transactional
//! ordering and recovery semantics: consume draft, read market data, insert
//! WatchRule, index its hash in the independent sidecar, then insert the W5h
//! funding row. It performs no signing, transaction construction, broadcast,
//! or executor action.
//!
//! `funding_window_seconds` is descriptive metadata derived from
//! `FUNDING_WINDOW_MS`. Any signing-page countdown MUST use the absolute
//! `expires_at_ms` deadline, never reconstruct a deadline from the window
//! length. The funding row's persisted `created_at_ms` / `expires_at_ms` are
//! the sole wall-clock authority for the response and signing-page payload.

use std::{
    str::FromStr,
    time::{SystemTime, UNIX_EPOCH},
};

use claw_state_store::{
    NewW5hFundingIntent, Stage2W5hFundingIntentRepository, Stage2WatchRuleRepository, StoreError,
    W5hFundingIntent, W5hIntentStatus,
};
use claw_types::{
    canonical_rule_hash, ActionSpec, Comparison, Condition, ConditionLogic, PubkeyBytes, RateKind,
    WatchRule, STAGE2_WATCH_RULE_SCHEMA_V2,
};
use schemars::JsonSchema;
use serde::Deserialize;
use serde_json::{json, Value};
use solana_sdk::pubkey::Pubkey;
use spl_associated_token_account::get_associated_token_address;
use uuid::{Uuid, Version};

use crate::{
    finalize_market::FinalizeMarketDataSource,
    propose::{
        validate_and_hash_draft, DraftIntent, ProposeIntentParams, CONTROLLED_USDC_ATA_BS58,
        CONTROLLED_WALLET_BS58,
    },
    sidecar::{ClaimOutcome, IndexOutcome, IntentSidecar},
};

pub(crate) const USDC_MINT_BS58: &str = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";
pub(crate) const SOLEND_RESERVE_BS58: &str = "BgxfHJDzm44T7XG68MYKx7YisTjZu73tVovyZSjJMpmw";
pub(crate) const SOLEND_LENDING_MARKET_BS58: &str = "4UpD2fh7xH3VP9QQaXtsS1YY3bxzWhtfpks7FatyKvdY";
pub(crate) const SOLEND_PROGRAM_ID_BS58: &str = "So1endDq2YkqhipRh3WViPa8hdiSpxWy6z3Z6tMCpAo";
pub(crate) const SOLEND_TARGET_OBLIGATION_BS58: &str =
    "BdFLjCcP9mCy557vNNGVbTUuvHxXsh8hc6jXzaPra1wN";
pub(crate) const MEMO_PROGRAM_ID_BS58: &str = "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr";
pub(crate) const WATCH_RULE_EXPIRY_SLOTS: u64 = 480;
const SIGNING_PAGE_BASE_URL: &str = "http://127.0.0.1:8080/index.html";
const FUNDING_WINDOW_MS: i64 = 180_000;
const FUNDING_WINDOW_SECONDS: i64 = FUNDING_WINDOW_MS / 1_000;
const CANONICAL_DEPOSIT_MAPPING_ERROR: &str =
    "the approved draft cannot be represented as the canonical SolendDeposit action";

/// All proposal fields stay flat on the MCP wire. The two IDs have distinct
/// jobs: `draft_id` controls one-shot finalization; `draft_hash` attests the
/// canonical proposal contents. `user_wallet` is the external funding wallet,
/// resolved from the authenticated session in the predecessor and therefore
/// intentionally excluded from the earlier draft hash.
///
/// Serde documents `flatten` plus `deny_unknown_fields` as unsupported. The
/// currently locked Serde implementation does reject unknown fields for this
/// exact shape; `finalize_params_reject_unknown_fields` is the upgrade guard.
#[derive(Debug, Clone, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct FinalizeIntentParams {
    #[serde(flatten)]
    pub(crate) proposal: ProposeIntentParams,
    /// Random v4 UUID returned by propose_intent. Never part of a hash.
    pub(crate) draft_id: String,
    /// Canonical draft hash returned by propose_intent.
    pub(crate) draft_hash: String,
    /// Public key of the Phantom wallet that will fund the controlled ATA.
    pub(crate) user_wallet: String,
}

pub(crate) trait FinalizeClock: Send + Sync {
    fn now_ms(&self) -> i64;
}

#[derive(Debug, Clone, Copy)]
pub(crate) struct SystemFinalizeClock;

impl FinalizeClock for SystemFinalizeClock {
    fn now_ms(&self) -> i64 {
        let millis = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system clock must be after the Unix epoch")
            .as_millis();
        i64::try_from(millis).unwrap_or(i64::MAX)
    }
}

#[derive(Debug, thiserror::Error)]
pub(crate) enum FinalizeInternalError {
    #[error("state-store operation failed")]
    StateStore(#[source] StoreError),
}

/// Execute the finalized-draft bridge.
///
/// Hash mismatch and all expected fail-closed conditions are normal JSON
/// results. Only an actual main state-store failure is promoted to MCP error by
/// the caller.
pub(crate) async fn finalize_intent_json<S, C>(
    params: &FinalizeIntentParams,
    market_source: Option<&S>,
    sidecar: &IntentSidecar,
    watch_rules: &Stage2WatchRuleRepository,
    funding_intents: &Stage2W5hFundingIntentRepository,
    clock: &C,
) -> Result<Value, FinalizeInternalError>
where
    S: FinalizeMarketDataSource,
    C: FinalizeClock,
{
    let (draft, recomputed_hash) = match validate_and_hash_draft(&params.proposal) {
        Ok(validated) => validated,
        Err(error) => {
            return Ok(json!({
                "status": "invalid_input",
                "reason": error.to_string(),
            }));
        }
    };

    if recomputed_hash != params.draft_hash {
        return Ok(json!({
            "status": "hash_mismatch",
            "draft_id": params.draft_id,
            "expected_draft_hash": recomputed_hash,
            "provided_draft_hash": params.draft_hash,
            "database_writes": 0,
        }));
    }

    if !is_v4_uuid(&params.draft_id) {
        return Ok(json!({
            "status": "invalid_input",
            "reason": "draft_id must be a random UUID v4 returned by propose_intent",
        }));
    }

    // Fail before claiming the draft or touching the network/main database if
    // a future proposal shape cannot be represented by the reviewed v2 action.
    if let Err(reason) = validate_canonical_solend_deposit_draft(&draft) {
        return Ok(json!({
            "status": "canonical_action_unsupported",
            "reason": reason,
            "draft_consumed": false,
            "database_writes": 0,
        }));
    }

    // These are MCP-only preconditions. The predecessor received an already
    // authenticated session wallet and could only start with market wiring
    // present, so consuming a draft for either failure would invent a new
    // destructive behavior rather than preserve a legacy one.
    let Some(market_source) = market_source else {
        return Ok(json!({
            "status": "config_missing",
            "reason": "SOLFRONTIER_RPC_URL is not set",
            "setup": "Set SOLFRONTIER_RPC_URL in the server environment, restart, then retry finalize with the same unconsumed draft_id",
            "draft_consumed": false,
        }));
    };
    let user_wallet = match Pubkey::from_str(params.user_wallet.trim()) {
        Ok(wallet) => wallet,
        Err(_) => {
            return Ok(json!({
                "status": "invalid_user_wallet",
                "reason": "user_wallet must be a valid Solana public key",
                "draft_consumed": false,
            }));
        }
    };
    let usdc_mint = Pubkey::from_str(USDC_MINT_BS58).expect("hard-coded USDC mint must parse");
    let user_usdc_ata = get_associated_token_address(&user_wallet, &usdc_mint);

    // Once the MCP-only preconditions pass, preserve the predecessor's
    // consume-before-network-read ordering. A later market or persistence
    // failure requires a freshly proposed draft; the tombstone is not rolled
    // back.
    let draft_consumed_at_ms = clock.now_ms();
    match sidecar
        .claim_draft(&params.draft_id, &params.draft_hash, draft_consumed_at_ms)
        .await
    {
        ClaimOutcome::Claimed => {}
        ClaimOutcome::AlreadyConsumed => {
            return Ok(json!({
                "status": "already_finalized_or_missing",
                "draft_id": params.draft_id,
            }));
        }
        ClaimOutcome::Conflict => {
            return Ok(json!({
                "status": "draft_id_conflict",
                "draft_id": params.draft_id,
                "reason": "draft_id is already bound to a different draft hash",
            }));
        }
        ClaimOutcome::Unavailable => {
            return Ok(json!({
                "status": "sidecar_unavailable",
                "reason": "the local finalize index is unavailable; no main database row was written",
            }));
        }
    }

    // Preserve the predecessor's pre-market clock sample so this authority fix
    // does not shift the persisted deadline's generation order or value. The
    // sample is deliberately not a response deadline source.
    let _finalize_started_at_ms = clock.now_ms();
    let snapshot = match market_source.fetch_snapshot().await {
        Ok(snapshot) => snapshot,
        Err(error) => {
            return Ok(json!({
                "status": "market_data_error",
                "error_class": error.category(),
                "reason": error.to_string(),
                "draft_consumed": true,
            }));
        }
    };

    let fresh_rule = match build_watch_rule(&draft, snapshot.last_checked_slot) {
        Ok(rule) => rule,
        Err(reason) => {
            return Ok(json!({
                "status": "canonical_action_unsupported",
                "reason": reason,
                "draft_consumed": true,
                "database_writes": 0,
            }));
        }
    };
    let (rule_for_identity, rule_persisted) =
        persist_rule_with_legacy_recovery(watch_rules, &fresh_rule).await;
    let expected_rule = build_watch_rule(&draft, rule_for_identity.created_at_slot)
        .expect("draft was prevalidated");
    if rule_persisted && rule_for_identity != expected_rule {
        return Ok(json!({
            "status": "existing_rule_conflict",
            "draft_id": params.draft_id,
            "reason": "the persisted WatchRule with this deterministic id does not match the approved canonical SolendDeposit rule shape",
            "draft_consumed": true,
        }));
    }
    let Some(canonical_amount_raw) = canonical_solend_deposit_amount_raw(&rule_for_identity) else {
        return Ok(json!({
            "status": "existing_rule_conflict",
            "draft_id": params.draft_id,
            "reason": "the persisted WatchRule violates the exact SolendDeposit action/rule amount invariant",
            "draft_consumed": true,
        }));
    };
    let intent_id = hex_lower(&rule_for_identity.rule_id);
    let rule_hash = hex_lower(&canonical_rule_hash(&rule_for_identity));

    // The hash index is derivative and cannot make the main DB authoritative.
    // Index only a rule confirmed through the public repository API. Failure
    // degrades future hash lookup to unsupported_ref but does not change the
    // predecessor's two main-row write semantics.
    if rule_persisted {
        match sidecar
            .index_hash(
                &rule_hash,
                &intent_id,
                &params.draft_id,
                &params.draft_hash,
                clock.now_ms(),
            )
            .await
        {
            IndexOutcome::Indexed | IndexOutcome::AlreadyPresent => {}
            IndexOutcome::Conflict | IndexOutcome::Unavailable => {
                tracing::warn!(
                    operation = "index finalized intent hash",
                    "finalize sidecar hash index unavailable; UUID lookup remains authoritative"
                );
            }
        }
    }

    // Preserve the predecessor's DB deadline semantics: the 180-second funding
    // window starts when the funding row is persisted, after market reads.
    // Unlike the predecessor DTO, every response below reads its timestamps
    // from that authoritative row.
    let persisted_created_at_ms = clock.now_ms();
    let persisted_expires_at_ms = persisted_created_at_ms.saturating_add(FUNDING_WINDOW_MS);
    let new_intent = NewW5hFundingIntent {
        intent_id: intent_id.clone(),
        rule_id_hex: intent_id.clone(),
        canonical_rule_hash_hex: rule_hash.clone(),
        user_wallet: user_wallet.to_string(),
        user_usdc_ata: user_usdc_ata.to_string(),
        controlled_wallet: CONTROLLED_WALLET_BS58.to_string(),
        controlled_usdc_ata: CONTROLLED_USDC_ATA_BS58.to_string(),
        amount_raw: canonical_amount_raw,
        threshold_bps: draft.threshold_bps,
        save_display_apy_bps_at_creation: snapshot.save_display_apy_bps,
        native_onchain_apr_bps_at_creation: snapshot.native_onchain_apr_bps,
        created_at_ms: persisted_created_at_ms,
        expires_at_ms: persisted_expires_at_ms,
    };

    let persistence = persist_funding_with_legacy_recovery(funding_intents, &new_intent).await?;
    let reused_existing_intent = matches!(persistence, FundingPersistOutcome::Existing(_));
    let current = persistence.into_row();
    if let Some(response) = unconfirmed_rule_guard(
        rule_persisted,
        params,
        &intent_id,
        &rule_hash,
        current.status.as_str(),
        reused_existing_intent,
    ) {
        return Ok(response);
    }
    if !funding_row_matches_identity(&current, &rule_for_identity, &intent_id, &rule_hash) {
        return Ok(json!({
            "status": "existing_intent_conflict",
            "draft_id": params.draft_id,
            "intent_id": intent_id,
            "reason": "the authoritative funding row does not match the persisted WatchRule; no funding instructions were issued",
            "draft_consumed": true,
        }));
    }

    let response_created_at_ms = current.created_at_ms;
    let response_expires_at_ms = current.expires_at_ms;
    let memo = format!("claw:w5h:{intent_id}:{rule_hash}");
    let request_wallet_matches_persisted = current.user_wallet == user_wallet.to_string();
    if reused_existing_intent && !request_wallet_matches_persisted {
        return Ok(json!({
            "status": "existing_intent_conflict",
            "draft_id": params.draft_id,
            "intent_id": intent_id,
            "persisted_status": current.status.as_str(),
            "reason": "this deterministic intent id is already bound to a different funding wallet; no funding instructions were issued",
            "draft_consumed": true,
        }));
    }
    // Re-check immediately before producing an actionable handoff so a market
    // read cannot bridge an existing intent across its persisted deadline.
    // The endpoint is inclusive: now >= expires_at_ms is expired.
    let actionability_checked_at_ms = clock.now_ms();
    if current.status != W5hIntentStatus::FundingRequired
        || current.expires_at_ms <= actionability_checked_at_ms
    {
        let reason = if current.expires_at_ms <= actionability_checked_at_ms {
            "the persisted funding deadline has elapsed; no funding instructions were issued"
        } else {
            "the persisted intent has already advanced beyond funding_required; no funding instructions were issued"
        };
        return Ok(json!({
            "status": current.status.as_str(),
            "draft_id": params.draft_id,
            "intent_id": intent_id,
            "rule_hash": rule_hash,
            "reused_existing_intent": reused_existing_intent,
            "funding_actionable": false,
            "created_at_ms": current.created_at_ms,
            "expires_at_ms": current.expires_at_ms,
            "reason": reason,
            "draft_consumed": true,
        }));
    }

    let funding = json!({
        "user_wallet": current.user_wallet,
        "user_usdc_ata": current.user_usdc_ata,
        "controlled_wallet": current.controlled_wallet,
        "controlled_usdc_ata": current.controlled_usdc_ata,
        "mint": USDC_MINT_BS58,
        "decimals": 6,
        "amount_raw": current.amount_raw.to_string(),
        "memo": memo,
        "memo_program_id": MEMO_PROGRAM_ID_BS58,
        "instruction_order": ["memo", "transfer_checked"],
        "funding_window_seconds": FUNDING_WINDOW_SECONDS,
        "expires_at_ms": response_expires_at_ms,
    });
    let signing_page_url =
        build_signing_page_url(current.status.as_str(), &intent_id, &rule_hash, &funding);

    Ok(json!({
        "status": current.status.as_str(),
        "draft_id": params.draft_id,
        "draft_hash": params.draft_hash,
        "intent_id": intent_id,
        "rule_hash": rule_hash,
        "rule_persisted": rule_persisted,
        "reused_existing_intent": reused_existing_intent,
        "funding_actionable": true,
        "created_at_ms": response_created_at_ms,
        "expires_at_ms": response_expires_at_ms,
        "funding": funding,
        "signing_page_url": signing_page_url,
        "signing": {
            "required": true,
            "performed_by_server": false,
            "request_wallet_matches_persisted": request_wallet_matches_persisted,
            "note": "The connected Phantom wallet must equal funding.user_wallet. This MCP server never signs.",
        },
    }))
}

fn build_signing_page_url(
    status: &str,
    intent_id: &str,
    rule_hash: &str,
    funding: &Value,
) -> String {
    let payload = json!({
        "status": status,
        "funding_actionable": true,
        "intent_id": intent_id,
        "rule_hash": rule_hash,
        "funding": funding,
    });
    let encoded_payload = percent_encode_fragment_component(&payload.to_string());
    format!("{SIGNING_PAGE_BASE_URL}#payload={encoded_payload}")
}

fn percent_encode_fragment_component(value: &str) -> String {
    const HEX: &[u8; 16] = b"0123456789ABCDEF";

    let mut encoded = String::with_capacity(value.len().saturating_mul(3));
    for &byte in value.as_bytes() {
        if byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.' | b'~') {
            encoded.push(char::from(byte));
        } else {
            encoded.push('%');
            encoded.push(char::from(HEX[usize::from(byte >> 4)]));
            encoded.push(char::from(HEX[usize::from(byte & 0x0f)]));
        }
    }
    encoded
}

fn unconfirmed_rule_guard(
    rule_persisted: bool,
    params: &FinalizeIntentParams,
    intent_id: &str,
    rule_hash: &str,
    persisted_funding_status: &str,
    reused_existing_intent: bool,
) -> Option<Value> {
    (!rule_persisted).then(|| {
        json!({
            "status": "rule_unconfirmed",
            "draft_id": params.draft_id,
            "draft_hash": params.draft_hash,
            "intent_id": intent_id,
            "rule_hash": rule_hash,
            "rule_persisted": false,
            "funding_intent_persisted": true,
            "persisted_funding_status": persisted_funding_status,
            "reused_existing_intent": reused_existing_intent,
            "funding_actionable": false,
            "draft_consumed": true,
            "reason": "the monitoring rule could not be confirmed; funding now would be stranded pending manual refund, so no funding instructions were issued",
        })
    })
}

fn validate_canonical_solend_deposit_draft(draft: &DraftIntent) -> Result<(), &'static str> {
    if draft.action != "deposit"
        || draft.protocol != "solend"
        || draft.asset != "USDC"
        || draft.display_source != "save"
        || draft.comparison != "gt"
        || draft.expiry_seconds_after_finalize != 180
        || draft.controlled_wallet != CONTROLLED_WALLET_BS58
        || draft.controlled_usdc_ata != CONTROLLED_USDC_ATA_BS58
    {
        return Err(CANONICAL_DEPOSIT_MAPPING_ERROR);
    }
    Ok(())
}

pub(crate) fn build_watch_rule(
    draft: &DraftIntent,
    last_checked_slot: u64,
) -> Result<WatchRule, &'static str> {
    validate_canonical_solend_deposit_draft(draft)?;

    let controlled = PubkeyBytes::from_base58(CONTROLLED_WALLET_BS58)
        .expect("hard-coded controlled wallet must parse");
    let reserve =
        PubkeyBytes::from_base58(SOLEND_RESERVE_BS58).expect("hard-coded reserve must parse");
    let lending_market = PubkeyBytes::from_base58(SOLEND_LENDING_MARKET_BS58)
        .expect("hard-coded lending market must parse");
    let solend_program_id = PubkeyBytes::from_base58(SOLEND_PROGRAM_ID_BS58)
        .expect("hard-coded Solend program id must parse");
    let input_mint =
        PubkeyBytes::from_base58(USDC_MINT_BS58).expect("hard-coded USDC mint must parse");
    let target_obligation = PubkeyBytes::from_base58(SOLEND_TARGET_OBLIGATION_BS58)
        .expect("hard-coded target obligation must parse");
    let input_amount_raw = draft.amount_raw;

    Ok(WatchRule {
        // PR-C closes the predecessor's first-class action gap: finalized
        // deposits now bind all six execution inputs in schema v2.
        schema_version: STAGE2_WATCH_RULE_SCHEMA_V2,
        rule_id: derive_rule_id(draft.threshold_bps, draft.amount_raw, &controlled),
        user: controlled,
        executor: controlled,
        delegated_wallet: controlled,
        created_at_slot: last_checked_slot,
        expires_at_slot: last_checked_slot.saturating_add(WATCH_RULE_EXPIRY_SLOTS),
        one_shot: true,
        condition_logic: ConditionLogic::All,
        conditions: vec![Condition::SolendReserveSupplyRate {
            reserve_pubkey: reserve,
            lending_market,
            solend_program_id,
            comparison: Comparison::Gt,
            threshold_bps: draft.threshold_bps,
            rate_kind: RateKind::Apr,
            formula_version: 1,
            max_reserve_staleness_slots: 16,
            required_refresh_same_tx: true,
        }],
        action: ActionSpec::SolendDeposit {
            target_obligation,
            reserve_pubkey: reserve,
            lending_market,
            solend_program_id,
            input_mint,
            input_amount_raw,
        },
        max_input_amount_raw: input_amount_raw,
        used_amount_raw: 0,
        destination: controlled,
        slippage_bps: 0,
    })
}

fn derive_rule_id(
    threshold_bps: u32,
    amount_raw: u64,
    controlled_wallet: &PubkeyBytes,
) -> [u8; 16] {
    let mut rule_id = [0_u8; 16];
    rule_id[0..4].copy_from_slice(&threshold_bps.to_le_bytes());
    rule_id[4..12].copy_from_slice(&amount_raw.to_le_bytes());
    rule_id[12..16].copy_from_slice(&controlled_wallet.0[0..4]);
    rule_id
}

async fn persist_rule_with_legacy_recovery(
    repository: &Stage2WatchRuleRepository,
    fresh: &WatchRule,
) -> (WatchRule, bool) {
    match repository.insert(fresh).await {
        Ok(()) => (fresh.clone(), true),
        Err(_) => match repository.get(&fresh.rule_id).await {
            Ok(Some(stored)) => (stored.rule, true),
            // Deliberately retained legacy flaw: a failed insert plus a
            // failed/missing readback still proceeds to the funding write.
            Ok(None) | Err(_) => (fresh.clone(), false),
        },
    }
}

enum FundingPersistOutcome {
    Inserted(W5hFundingIntent),
    Existing(W5hFundingIntent),
}

impl FundingPersistOutcome {
    fn into_row(self) -> W5hFundingIntent {
        match self {
            Self::Inserted(row) | Self::Existing(row) => row,
        }
    }
}

async fn persist_funding_with_legacy_recovery(
    repository: &Stage2W5hFundingIntentRepository,
    fresh: &NewW5hFundingIntent,
) -> Result<FundingPersistOutcome, FinalizeInternalError> {
    match repository.insert(fresh).await {
        Ok(()) => match repository.get(&fresh.intent_id).await {
            Ok(Some(persisted)) => Ok(FundingPersistOutcome::Inserted(persisted)),
            Ok(None) => Err(FinalizeInternalError::StateStore(StoreError::NotFound {
                entity: "stage2_w5h_funding_intents".to_owned(),
                id: fresh.intent_id.clone(),
            })),
            Err(read_error) => Err(FinalizeInternalError::StateStore(read_error)),
        },
        Err(insert_error) => match repository.get(&fresh.intent_id).await {
            Ok(Some(existing)) => Ok(FundingPersistOutcome::Existing(existing)),
            Ok(None) => Err(FinalizeInternalError::StateStore(insert_error)),
            Err(read_error) => Err(FinalizeInternalError::StateStore(read_error)),
        },
    }
}

fn funding_row_matches_identity(
    funding: &W5hFundingIntent,
    rule: &WatchRule,
    intent_id: &str,
    rule_hash: &str,
) -> bool {
    if funding.intent_id != intent_id
        || funding.rule_id_hex != intent_id
        || !funding
            .canonical_rule_hash_hex
            .eq_ignore_ascii_case(rule_hash)
        || funding.controlled_wallet != CONTROLLED_WALLET_BS58
        || funding.controlled_usdc_ata != CONTROLLED_USDC_ATA_BS58
        || !has_exact_solend_deposit_amount_invariant(rule, funding.amount_raw)
    {
        return false;
    }

    let Some(rule_threshold_bps) = rule
        .conditions
        .first()
        .and_then(|condition| match condition {
            Condition::SolendReserveSupplyRate { threshold_bps, .. } => Some(*threshold_bps),
            _ => None,
        })
    else {
        return false;
    };
    if funding.threshold_bps != rule_threshold_bps {
        return false;
    }

    let Ok(user_wallet) = Pubkey::from_str(&funding.user_wallet) else {
        return false;
    };
    get_associated_token_address(
        &user_wallet,
        &Pubkey::from_str(USDC_MINT_BS58).expect("hard-coded USDC mint must parse"),
    )
    .to_string()
        == funding.user_usdc_ata
}

fn canonical_solend_deposit_amount_raw(rule: &WatchRule) -> Option<u64> {
    match &rule.action {
        ActionSpec::SolendDeposit {
            input_amount_raw, ..
        } if *input_amount_raw == rule.max_input_amount_raw => Some(*input_amount_raw),
        _ => None,
    }
}

fn has_exact_solend_deposit_amount_invariant(rule: &WatchRule, funding_amount_raw: u64) -> bool {
    canonical_solend_deposit_amount_raw(rule) == Some(funding_amount_raw)
}

fn is_v4_uuid(value: &str) -> bool {
    Uuid::parse_str(value)
        .ok()
        .is_some_and(|id| id.get_version() == Some(Version::Random))
}

pub(crate) fn hex_lower(bytes: &[u8]) -> String {
    use std::fmt::Write;

    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(&mut output, "{byte:02x}").expect("writing to String cannot fail");
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        finalize_market::{FinalizeMarketReadError, FinalizeMarketSnapshot},
        propose::{propose_intent_json, tests::valid_params},
        sidecar::{derive_sidecar_path, HashLookup},
        status::query_intent_status,
    };
    use claw_state_store::{Database, DatabaseConfig};
    use claw_types::canonical_rule_bytes;
    use std::{
        fs,
        path::PathBuf,
        sync::atomic::{AtomicU64, AtomicUsize, Ordering},
    };

    const TEST_USER_WALLET: &str = "C4QQjzWxnJ5QFAbkzhQJ3wTzyX6nw1vyFvJwbPXJGPNW";
    const FIRST_DRAFT_ID: &str = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
    const SECOND_DRAFT_ID: &str = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
    const THIRD_DRAFT_ID: &str = "cccccccc-cccc-4ccc-8ccc-cccccccccccc";
    const EXPECTED_INTENT_ID: &str = "3200000020a10700000000009a62dace";
    // Generated by:
    // cargo test -p solfrontier-mcp finalize::tests::print_finalize_v2_golden -- --nocapture
    const EXPECTED_RULE_HASH: &str = "GENERATE_WITH_PRINT_FINALIZE_V2_GOLDEN";
    const EXPECTED_USER_USDC_ATA: &str = "4bDArC4UVoBjecHUZaCKqhuhTYPoiKS4qpQQpxuvm1qn";
    const FINALIZE_STARTED_AT_MS: i64 = 1_700_000_000_000;
    const CLOCK_STEP_MS: i64 = 1_000;
    const FIRST_MARKET_SLOT: u64 = 419_000_000;

    static TEST_DB_SEQUENCE: AtomicU64 = AtomicU64::new(0);

    struct TempDatabaseFile {
        path: PathBuf,
    }

    impl TempDatabaseFile {
        fn unique() -> Self {
            let sequence = TEST_DB_SEQUENCE.fetch_add(1, Ordering::Relaxed);
            let path = std::env::temp_dir().join(format!(
                "solfrontier-mcp-finalize-{}-{sequence}.db",
                std::process::id()
            ));
            Self { path }
        }

        fn config(&self) -> DatabaseConfig {
            DatabaseConfig {
                path: self.path.to_string_lossy().into_owned(),
                max_connections: 1,
            }
        }
    }

    impl Drop for TempDatabaseFile {
        fn drop(&mut self) {
            let sidecar = derive_sidecar_path(&self.path);
            for path in [
                self.path.clone(),
                PathBuf::from(format!("{}-wal", self.path.display())),
                PathBuf::from(format!("{}-shm", self.path.display())),
                sidecar.clone(),
                PathBuf::from(format!("{}-journal", sidecar.display())),
                PathBuf::from(format!("{}-wal", sidecar.display())),
                PathBuf::from(format!("{}-shm", sidecar.display())),
            ] {
                let _ = fs::remove_file(path);
            }
        }
    }

    struct MockMarketSource {
        snapshots: Vec<FinalizeMarketSnapshot>,
        calls: AtomicUsize,
    }

    impl MockMarketSource {
        fn new(snapshots: Vec<FinalizeMarketSnapshot>) -> Self {
            Self {
                snapshots,
                calls: AtomicUsize::new(0),
            }
        }

        fn calls(&self) -> usize {
            self.calls.load(Ordering::SeqCst)
        }
    }

    impl FinalizeMarketDataSource for MockMarketSource {
        async fn fetch_snapshot(&self) -> Result<FinalizeMarketSnapshot, FinalizeMarketReadError> {
            let index = self.calls.fetch_add(1, Ordering::SeqCst);
            self.snapshots
                .get(index)
                .copied()
                .ok_or(FinalizeMarketReadError::SlotRequestFailed)
        }
    }

    struct StepClock {
        base_ms: i64,
        step_ms: i64,
        calls: AtomicUsize,
    }

    impl StepClock {
        fn new(base_ms: i64, step_ms: i64) -> Self {
            Self {
                base_ms,
                step_ms,
                calls: AtomicUsize::new(0),
            }
        }
    }

    impl FinalizeClock for StepClock {
        fn now_ms(&self) -> i64 {
            let index = self.calls.fetch_add(1, Ordering::SeqCst);
            self.base_ms
                .saturating_add(self.step_ms.saturating_mul(index as i64))
        }
    }

    async fn test_store() -> (
        TempDatabaseFile,
        Database,
        Stage2WatchRuleRepository,
        Stage2W5hFundingIntentRepository,
        IntentSidecar,
    ) {
        let file = TempDatabaseFile::unique();
        let db = Database::open(&file.config())
            .await
            .expect("temporary SQLite database must open");
        let watch_rules = Stage2WatchRuleRepository::new(db.pool().clone());
        let funding_intents = Stage2W5hFundingIntentRepository::new(db.pool().clone());
        let sidecar = IntentSidecar::for_database_path(&file.path);
        (file, db, watch_rules, funding_intents, sidecar)
    }

    async fn close_test_store(
        db: Database,
        watch_rules: Stage2WatchRuleRepository,
        funding_intents: Stage2W5hFundingIntentRepository,
        sidecar: IntentSidecar,
    ) {
        drop(sidecar);
        drop(watch_rules);
        drop(funding_intents);
        db.pool().close().await;
    }

    fn params_with_id(draft_id: &str) -> FinalizeIntentParams {
        let proposal = valid_params();
        let (_, draft_hash) = validate_and_hash_draft(&proposal).expect("valid proposal must hash");
        FinalizeIntentParams {
            proposal,
            draft_id: draft_id.to_owned(),
            draft_hash,
            user_wallet: TEST_USER_WALLET.to_owned(),
        }
    }

    fn params_from_propose_response() -> FinalizeIntentParams {
        let proposal = valid_params();
        let response = propose_intent_json(&proposal);
        assert_eq!(response["status"], "ok");
        FinalizeIntentParams {
            proposal,
            draft_id: response["draft_id"]
                .as_str()
                .expect("propose must return a draft id")
                .to_owned(),
            draft_hash: response["draft_hash"]
                .as_str()
                .expect("propose must return a draft hash")
                .to_owned(),
            user_wallet: TEST_USER_WALLET.to_owned(),
        }
    }

    fn params_json_with_id(draft_id: &str) -> Value {
        let params = params_with_id(draft_id);
        json!({
            "action": "deposit",
            "protocol": "solend",
            "asset": "USDC",
            "display_source": "save",
            "comparison": "gt",
            "amount": "0.5",
            "threshold_bps": 50,
            "expiry_seconds_after_finalize": 180,
            "controlled_wallet": CONTROLLED_WALLET_BS58,
            "controlled_usdc_ata": CONTROLLED_USDC_ATA_BS58,
            "original_user_message": "If Save APY > 0.5%, deposit 0.5 USDC",
            "draft_id": draft_id,
            "draft_hash": params.draft_hash,
            "user_wallet": TEST_USER_WALLET,
        })
    }

    fn snapshot(slot: u64, native_apr_bps: u32, save_apy_bps: u32) -> FinalizeMarketSnapshot {
        FinalizeMarketSnapshot {
            last_checked_slot: slot,
            native_onchain_apr_bps: native_apr_bps,
            save_display_apy_bps: save_apy_bps,
        }
    }

    fn expected_rule() -> WatchRule {
        let controlled =
            PubkeyBytes::from_base58(CONTROLLED_WALLET_BS58).expect("pinned controlled wallet");
        let reserve = PubkeyBytes::from_base58(SOLEND_RESERVE_BS58).expect("pinned reserve");
        let lending_market =
            PubkeyBytes::from_base58(SOLEND_LENDING_MARKET_BS58).expect("pinned lending market");
        WatchRule {
            schema_version: STAGE2_WATCH_RULE_SCHEMA_V2,
            rule_id: [
                0x32, 0x00, 0x00, 0x00, 0x20, 0xa1, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x9a, 0x62,
                0xda, 0xce,
            ],
            user: controlled,
            executor: controlled,
            delegated_wallet: controlled,
            created_at_slot: FIRST_MARKET_SLOT,
            expires_at_slot: FIRST_MARKET_SLOT + WATCH_RULE_EXPIRY_SLOTS,
            one_shot: true,
            condition_logic: ConditionLogic::All,
            conditions: vec![Condition::SolendReserveSupplyRate {
                reserve_pubkey: reserve,
                lending_market,
                solend_program_id: PubkeyBytes::from_base58(SOLEND_PROGRAM_ID_BS58)
                    .expect("pinned Solend program"),
                comparison: Comparison::Gt,
                threshold_bps: 50,
                rate_kind: RateKind::Apr,
                formula_version: 1,
                max_reserve_staleness_slots: 16,
                required_refresh_same_tx: true,
            }],
            action: ActionSpec::SolendDeposit {
                target_obligation: PubkeyBytes::from_base58(SOLEND_TARGET_OBLIGATION_BS58)
                    .expect("pinned target obligation"),
                reserve_pubkey: reserve,
                lending_market,
                solend_program_id: PubkeyBytes::from_base58(SOLEND_PROGRAM_ID_BS58)
                    .expect("pinned Solend program"),
                input_mint: PubkeyBytes::from_base58(USDC_MINT_BS58).expect("pinned USDC mint"),
                input_amount_raw: 500_000,
            },
            max_input_amount_raw: 500_000,
            used_amount_raw: 0,
            destination: controlled,
            slippage_bps: 0,
        }
    }

    #[test]
    fn print_finalize_v2_golden() {
        let proposal = valid_params();
        let (draft, _) = validate_and_hash_draft(&proposal).expect("valid proposal must hash");
        let rule =
            build_watch_rule(&draft, FIRST_MARKET_SLOT).expect("approved draft must map to v2");

        println!(
            "canonical_rule_bytes_hex={}",
            hex_lower(&canonical_rule_bytes(&rule))
        );
        println!(
            "canonical_rule_hash_hex={}",
            hex_lower(&canonical_rule_hash(&rule))
        );
        assert_eq!(
            hex_lower(&canonical_rule_hash(&rule)),
            EXPECTED_RULE_HASH,
            "replace the placeholder only with this program-generated value"
        );
    }

    #[test]
    fn unsupported_draft_shape_cannot_build_a_watch_rule() {
        let proposal = valid_params();
        let (draft, _) = validate_and_hash_draft(&proposal).expect("valid proposal must hash");

        let mut unsupported_action = draft.clone();
        unsupported_action.action = "withdraw";
        assert_eq!(
            build_watch_rule(&unsupported_action, FIRST_MARKET_SLOT)
                .expect_err("an unsupported action must fail closed"),
            CANONICAL_DEPOSIT_MAPPING_ERROR
        );

        let mut unsupported_protocol = draft;
        unsupported_protocol.protocol = "unknown";
        assert_eq!(
            build_watch_rule(&unsupported_protocol, FIRST_MARKET_SLOT)
                .expect_err("an unsupported protocol must fail closed"),
            CANONICAL_DEPOSIT_MAPPING_ERROR
        );
    }

    #[test]
    fn exact_deposit_amount_invariant_rejects_each_mismatch() {
        let rule = expected_rule();
        assert!(has_exact_solend_deposit_amount_invariant(&rule, 500_000));

        let mut wrong_action_amount = rule.clone();
        let ActionSpec::SolendDeposit {
            input_amount_raw, ..
        } = &mut wrong_action_amount.action
        else {
            panic!("fixture must be a canonical deposit");
        };
        *input_amount_raw += 1;
        assert!(!has_exact_solend_deposit_amount_invariant(
            &wrong_action_amount,
            500_000
        ));

        let mut wrong_rule_cap = rule.clone();
        wrong_rule_cap.max_input_amount_raw += 1;
        assert!(!has_exact_solend_deposit_amount_invariant(
            &wrong_rule_cap,
            500_000
        ));

        assert!(!has_exact_solend_deposit_amount_invariant(&rule, 500_001));
    }

    fn signing_page_payload(response: &Value) -> Value {
        let url = response["signing_page_url"]
            .as_str()
            .expect("actionable response must include a signing-page URL");
        let encoded = url
            .strip_prefix(SIGNING_PAGE_BASE_URL)
            .and_then(|suffix| suffix.strip_prefix("#payload="))
            .expect("signing instructions must live only in the URL fragment");
        let bytes = encoded.as_bytes();
        let mut decoded = Vec::with_capacity(bytes.len());
        let mut index = 0;
        while index < bytes.len() {
            if bytes[index] == b'%' {
                let hex = std::str::from_utf8(
                    bytes
                        .get(index + 1..index + 3)
                        .expect("percent escape must contain two hex digits"),
                )
                .expect("percent escape must be ASCII");
                decoded.push(u8::from_str_radix(hex, 16).expect("percent escape must be hex"));
                index += 3;
            } else {
                decoded.push(bytes[index]);
                index += 1;
            }
        }
        serde_json::from_slice(&decoded).expect("decoded fragment must be JSON")
    }

    #[test]
    fn finalize_params_reject_unknown_fields() {
        let valid = params_json_with_id(FIRST_DRAFT_ID);
        serde_json::from_value::<FinalizeIntentParams>(valid.clone())
            .expect("the flat wire shape must deserialize");

        let mut with_unknown = valid;
        with_unknown
            .as_object_mut()
            .expect("fixture is an object")
            .insert("unexpected_field".into(), json!(true));
        let error = serde_json::from_value::<FinalizeIntentParams>(with_unknown)
            .expect_err("unknown finalize fields must fail closed");
        let message = error.to_string();
        assert!(
            message.contains("unknown field") && message.contains("unexpected_field"),
            "unexpected deserialization error: {message}"
        );
    }

    #[test]
    fn finalize_params_reject_unsupported_action_instead_of_falling_back() {
        let mut unsupported = params_json_with_id(FIRST_DRAFT_ID);
        unsupported["action"] = json!("withdraw");
        let error = serde_json::from_value::<FinalizeIntentParams>(unsupported)
            .expect_err("the typed wire schema must reject an unsupported action");
        assert!(
            error.to_string().contains("unknown variant"),
            "unexpected deserialization error: {error}"
        );
    }

    #[test]
    fn unconfirmed_rule_guard_never_exposes_funding_instructions() {
        let params = params_with_id(FIRST_DRAFT_ID);
        assert!(
            unconfirmed_rule_guard(
                true,
                &params,
                EXPECTED_INTENT_ID,
                EXPECTED_RULE_HASH,
                "funding_required",
                false,
            )
            .is_none(),
            "a confirmed rule must continue to the normal response path"
        );

        let response = unconfirmed_rule_guard(
            false,
            &params,
            EXPECTED_INTENT_ID,
            EXPECTED_RULE_HASH,
            "funding_required",
            false,
        )
        .expect("an unconfirmed rule must be blocked at the response boundary");
        assert_eq!(response["status"], "rule_unconfirmed");
        assert_eq!(response["rule_persisted"], false);
        assert_eq!(response["funding_intent_persisted"], true);
        assert_eq!(response["funding_actionable"], false);
        assert_eq!(response["draft_consumed"], true);
        assert!(
            response.get("funding").is_none(),
            "an unconfirmed monitoring rule must never expose funding instructions"
        );
        assert!(
            response.get("signing").is_none(),
            "an unconfirmed monitoring rule must never invite a signature"
        );
        assert!(
            response.get("signing_page_url").is_none(),
            "an unconfirmed monitoring rule must never expose a signing-page handoff"
        );
        assert!(response["reason"]
            .as_str()
            .expect("reason is a string")
            .contains("stranded pending manual refund"));
    }

    #[tokio::test]
    async fn hash_mismatch_writes_nothing_and_never_reads_market() {
        let (file, db, watch_rules, funding_intents, sidecar) = test_store().await;
        let mut params = params_with_id(FIRST_DRAFT_ID);
        params.draft_hash = "0".repeat(64);
        let market = MockMarketSource::new(vec![snapshot(FIRST_MARKET_SLOT, 165, 210)]);
        let clock = StepClock::new(FINALIZE_STARTED_AT_MS, CLOCK_STEP_MS);

        let response = finalize_intent_json(
            &params,
            Some(&market),
            &sidecar,
            &watch_rules,
            &funding_intents,
            &clock,
        )
        .await
        .expect("hash mismatch is a normal response");

        assert_eq!(response["status"], "hash_mismatch");
        assert_eq!(response["database_writes"], 0);
        assert_eq!(market.calls(), 0, "market seam must not be called");
        let expected = expected_rule();
        assert!(watch_rules
            .get(&expected.rule_id)
            .await
            .expect("watch-rule lookup")
            .is_none());
        assert!(funding_intents
            .get(EXPECTED_INTENT_ID)
            .await
            .expect("funding-intent lookup")
            .is_none());
        assert!(
            !derive_sidecar_path(&file.path).exists(),
            "hash mismatch must not create the sidecar"
        );

        close_test_store(db, watch_rules, funding_intents, sidecar).await;
    }

    #[tokio::test]
    async fn corrupt_sidecar_blocks_finalize_before_main_database_writes() {
        let (file, db, watch_rules, funding_intents, sidecar) = test_store().await;
        fs::write(derive_sidecar_path(&file.path), b"not a sqlite database")
            .expect("write corrupt sidecar fixture");
        let params = params_with_id(FIRST_DRAFT_ID);
        let market = MockMarketSource::new(vec![snapshot(FIRST_MARKET_SLOT, 165, 210)]);
        let clock = StepClock::new(FINALIZE_STARTED_AT_MS, CLOCK_STEP_MS);

        let response = finalize_intent_json(
            &params,
            Some(&market),
            &sidecar,
            &watch_rules,
            &funding_intents,
            &clock,
        )
        .await
        .expect("an unavailable sidecar is a normal fail-closed response");

        assert_eq!(response["status"], "sidecar_unavailable");
        assert_eq!(market.calls(), 0, "market seam must not be called");
        assert!(
            response.get("funding").is_none(),
            "sidecar failure must not expose funding instructions"
        );
        assert!(
            response.get("signing").is_none(),
            "sidecar failure must not invite a signature"
        );
        assert!(watch_rules
            .get(&expected_rule().rule_id)
            .await
            .expect("watch-rule lookup")
            .is_none());
        assert!(funding_intents
            .get(EXPECTED_INTENT_ID)
            .await
            .expect("funding-intent lookup")
            .is_none());

        close_test_store(db, watch_rules, funding_intents, sidecar).await;
    }

    #[tokio::test]
    async fn market_data_error_consumes_draft_without_main_database_writes() {
        let (file, db, watch_rules, funding_intents, sidecar) = test_store().await;
        let params = params_with_id(FIRST_DRAFT_ID);
        let failing_market = MockMarketSource::new(vec![]);
        let clock = StepClock::new(FINALIZE_STARTED_AT_MS, CLOCK_STEP_MS);

        let response = finalize_intent_json(
            &params,
            Some(&failing_market),
            &sidecar,
            &watch_rules,
            &funding_intents,
            &clock,
        )
        .await
        .expect("market failure is a normal fail-closed response");

        assert_eq!(response["status"], "market_data_error");
        assert_eq!(response["error_class"], "slot_request_failed");
        assert_eq!(response["draft_consumed"], true);
        assert_eq!(failing_market.calls(), 1);
        assert!(
            response.get("funding").is_none(),
            "market failure must not expose funding instructions"
        );
        assert!(
            response.get("signing").is_none(),
            "market failure must not invite a signature"
        );
        assert!(
            derive_sidecar_path(&file.path).exists(),
            "the consume-before-market tombstone must be durable"
        );
        assert!(watch_rules
            .get(&expected_rule().rule_id)
            .await
            .expect("watch-rule lookup")
            .is_none());
        assert!(funding_intents
            .get(EXPECTED_INTENT_ID)
            .await
            .expect("funding-intent lookup")
            .is_none());

        let retry_market = MockMarketSource::new(vec![snapshot(FIRST_MARKET_SLOT, 165, 210)]);
        let retry = finalize_intent_json(
            &params,
            Some(&retry_market),
            &sidecar,
            &watch_rules,
            &funding_intents,
            &clock,
        )
        .await
        .expect("same-draft retry is a normal response");
        assert_eq!(retry["status"], "already_finalized_or_missing");
        assert_eq!(
            retry_market.calls(),
            0,
            "the consumed draft must be rejected before a second market read"
        );

        close_test_store(db, watch_rules, funding_intents, sidecar).await;
    }

    #[tokio::test]
    async fn missing_market_config_does_not_consume_draft_or_create_sidecar() {
        let (file, db, watch_rules, funding_intents, sidecar) = test_store().await;
        let params = params_with_id(FIRST_DRAFT_ID);
        let market = MockMarketSource::new(vec![snapshot(FIRST_MARKET_SLOT, 165, 210)]);
        let clock = StepClock::new(FINALIZE_STARTED_AT_MS, CLOCK_STEP_MS);

        let response = finalize_intent_json::<MockMarketSource, _>(
            &params,
            None,
            &sidecar,
            &watch_rules,
            &funding_intents,
            &clock,
        )
        .await
        .expect("missing configuration is a normal response");

        assert_eq!(response["status"], "config_missing");
        assert_eq!(response["draft_consumed"], false);
        assert_eq!(market.calls(), 0);
        assert!(
            !derive_sidecar_path(&file.path).exists(),
            "configuration preflight must not create the sidecar"
        );

        let retry = finalize_intent_json(
            &params,
            Some(&market),
            &sidecar,
            &watch_rules,
            &funding_intents,
            &clock,
        )
        .await
        .expect("the same unconsumed draft must remain usable");
        assert_eq!(retry["status"], "funding_required");

        close_test_store(db, watch_rules, funding_intents, sidecar).await;
    }

    #[tokio::test]
    async fn invalid_user_wallet_does_not_consume_draft_or_create_sidecar() {
        let (file, db, watch_rules, funding_intents, sidecar) = test_store().await;
        let mut params = params_with_id(FIRST_DRAFT_ID);
        params.user_wallet = "not-a-solana-public-key".to_owned();
        let market = MockMarketSource::new(vec![snapshot(FIRST_MARKET_SLOT, 165, 210)]);
        let clock = StepClock::new(FINALIZE_STARTED_AT_MS, CLOCK_STEP_MS);

        let response = finalize_intent_json(
            &params,
            Some(&market),
            &sidecar,
            &watch_rules,
            &funding_intents,
            &clock,
        )
        .await
        .expect("invalid wallet is a normal response");

        assert_eq!(response["status"], "invalid_user_wallet");
        assert_eq!(response["draft_consumed"], false);
        assert_eq!(market.calls(), 0);
        assert!(
            !derive_sidecar_path(&file.path).exists(),
            "wallet syntax preflight must not create the sidecar"
        );
        assert!(watch_rules
            .get(&expected_rule().rule_id)
            .await
            .expect("watch-rule lookup")
            .is_none());
        assert!(funding_intents
            .get(EXPECTED_INTENT_ID)
            .await
            .expect("funding-intent lookup")
            .is_none());

        params.user_wallet = TEST_USER_WALLET.to_owned();
        let retry = finalize_intent_json(
            &params,
            Some(&market),
            &sidecar,
            &watch_rules,
            &funding_intents,
            &clock,
        )
        .await
        .expect("the same unconsumed draft must remain usable");
        assert_eq!(retry["status"], "funding_required");

        close_test_store(db, watch_rules, funding_intents, sidecar).await;
    }

    #[tokio::test]
    async fn successful_finalize_persists_exact_golden_rows_and_hash_lookup() {
        let (file, db, watch_rules, funding_intents, sidecar) = test_store().await;
        let params = params_from_propose_response();
        let market = MockMarketSource::new(vec![snapshot(FIRST_MARKET_SLOT, 165, 210)]);
        let clock = StepClock::new(FINALIZE_STARTED_AT_MS, CLOCK_STEP_MS);

        let response = finalize_intent_json(
            &params,
            Some(&market),
            &sidecar,
            &watch_rules,
            &funding_intents,
            &clock,
        )
        .await
        .expect("finalize must succeed");

        assert_eq!(response["status"], "funding_required");
        assert_eq!(response["intent_id"], EXPECTED_INTENT_ID);
        assert_eq!(response["rule_hash"], EXPECTED_RULE_HASH);
        assert_eq!(
            response["funding"]["memo"],
            format!("claw:w5h:{EXPECTED_INTENT_ID}:{EXPECTED_RULE_HASH}")
        );
        assert_eq!(
            response["created_at_ms"],
            FINALIZE_STARTED_AT_MS + 3 * CLOCK_STEP_MS
        );
        assert_eq!(
            response["expires_at_ms"],
            FINALIZE_STARTED_AT_MS + 3 * CLOCK_STEP_MS + FUNDING_WINDOW_MS
        );
        assert_eq!(response["reused_existing_intent"], false);
        assert_eq!(response["funding"]["amount_raw"], "500000");
        assert_eq!(
            response["funding"]["controlled_wallet"],
            CONTROLLED_WALLET_BS58
        );
        assert_eq!(
            response["funding"]["controlled_usdc_ata"],
            CONTROLLED_USDC_ATA_BS58
        );
        assert_eq!(response["funding"]["user_usdc_ata"], EXPECTED_USER_USDC_ATA);
        assert_eq!(
            response["funding"]["instruction_order"],
            json!(["memo", "transfer_checked"]),
            "the canonical W5h Memo must remain instruction index 0"
        );
        assert_eq!(
            response["funding"]["funding_window_seconds"],
            FUNDING_WINDOW_SECONDS
        );
        assert!(
            response["funding"].get("expiry_seconds").is_none(),
            "the ambiguous legacy output name must not reappear"
        );
        let signing_payload = signing_page_payload(&response);
        assert_eq!(signing_payload["status"], "funding_required");
        assert_eq!(signing_payload["funding_actionable"], true);
        assert_eq!(signing_payload["intent_id"], EXPECTED_INTENT_ID);
        assert_eq!(signing_payload["rule_hash"], EXPECTED_RULE_HASH);
        assert_eq!(
            signing_payload["funding"], response["funding"],
            "the fragment must carry the complete funding instruction without reconstruction"
        );
        assert_eq!(
            signing_payload["funding"]["memo"],
            format!("claw:w5h:{EXPECTED_INTENT_ID}:{EXPECTED_RULE_HASH}"),
            "the signing page must receive the finalized memo verbatim"
        );
        assert_eq!(
            signing_payload["funding"]["instruction_order"],
            json!(["memo", "transfer_checked"]),
            "the signing page must preserve Memo at instruction index 0"
        );
        assert_eq!(signing_payload["funding"]["decimals"], 6);
        assert_eq!(
            signing_payload["funding"]["expires_at_ms"],
            FINALIZE_STARTED_AT_MS + 3 * CLOCK_STEP_MS + FUNDING_WINDOW_MS
        );
        assert_eq!(signing_payload["funding"]["user_wallet"], TEST_USER_WALLET);
        assert_eq!(market.calls(), 1);

        let expected_rule = expected_rule();
        let stored_rule = watch_rules
            .get(&expected_rule.rule_id)
            .await
            .expect("watch-rule lookup")
            .expect("watch rule must exist");
        assert_eq!(stored_rule.rule, expected_rule);
        assert_eq!(
            hex_lower(&stored_rule.canonical_rule_hash),
            EXPECTED_RULE_HASH
        );

        let stored_funding = funding_intents
            .get(EXPECTED_INTENT_ID)
            .await
            .expect("funding-intent lookup")
            .expect("funding intent must exist");
        assert_eq!(stored_funding.intent_id, EXPECTED_INTENT_ID);
        assert_eq!(stored_funding.rule_id_hex, EXPECTED_INTENT_ID);
        assert_eq!(stored_funding.canonical_rule_hash_hex, EXPECTED_RULE_HASH);
        assert_eq!(stored_funding.user_wallet, TEST_USER_WALLET);
        assert_eq!(stored_funding.user_usdc_ata, EXPECTED_USER_USDC_ATA);
        assert_eq!(stored_funding.controlled_wallet, CONTROLLED_WALLET_BS58);
        assert_eq!(stored_funding.controlled_usdc_ata, CONTROLLED_USDC_ATA_BS58);
        assert_eq!(stored_funding.amount_raw, 500_000);
        assert_eq!(stored_funding.threshold_bps, 50);
        assert_eq!(stored_funding.native_onchain_apr_bps_at_creation, 165);
        assert_eq!(stored_funding.save_display_apy_bps_at_creation, 210);
        assert_eq!(
            stored_funding.created_at_ms,
            FINALIZE_STARTED_AT_MS + 3 * CLOCK_STEP_MS
        );
        assert_eq!(
            stored_funding.expires_at_ms,
            FINALIZE_STARTED_AT_MS + 3 * CLOCK_STEP_MS + FUNDING_WINDOW_MS
        );
        assert_eq!(stored_funding.status, W5hIntentStatus::FundingRequired);
        assert!(stored_funding.funding_signature.is_none());
        assert!(stored_funding.funding_finalized_slot.is_none());
        assert!(stored_funding.execution_signature.is_none());
        assert!(stored_funding.refund_signature.is_none());
        assert!(stored_funding.last_error.is_none());
        assert_eq!(
            response["created_at_ms"], stored_funding.created_at_ms,
            "the persisted funding row is the sole created-at authority"
        );
        assert_eq!(
            response["expires_at_ms"], stored_funding.expires_at_ms,
            "the response deadline must equal the persisted funding deadline"
        );
        assert_eq!(
            response["funding"]["expires_at_ms"], stored_funding.expires_at_ms,
            "the nested funding instruction must use the persisted deadline"
        );
        assert_eq!(
            signing_payload["funding"]["expires_at_ms"], stored_funding.expires_at_ms,
            "the signing URL must carry the persisted deadline verbatim"
        );

        assert_eq!(
            sidecar.lookup_hash(EXPECTED_RULE_HASH).await,
            HashLookup::Found {
                intent_id: EXPECTED_INTENT_ID.to_owned()
            }
        );
        let status =
            query_intent_status(&funding_intents, &watch_rules, &sidecar, EXPECTED_RULE_HASH)
                .await
                .expect("hash status lookup must succeed");
        assert_eq!(status.status, "funding_required");
        assert_eq!(
            status.resolved_intent_id.as_deref(),
            Some(EXPECTED_INTENT_ID)
        );
        assert_eq!(
            status.canonical_rule_hash.as_deref(),
            Some(EXPECTED_RULE_HASH)
        );
        assert_eq!(status.amount_raw, Some(500_000));
        assert_eq!(status.input_mint.as_deref(), Some(USDC_MINT_BS58));

        close_test_store(db, watch_rules, funding_intents, sidecar).await;
        drop(file);
    }

    #[tokio::test]
    async fn same_draft_rejects_but_fresh_draft_with_same_semantics_recovers_existing_rows() {
        let (_file, db, watch_rules, funding_intents, sidecar) = test_store().await;
        let first = params_with_id(FIRST_DRAFT_ID);
        let second = params_with_id(SECOND_DRAFT_ID);
        let mut different_wallet = params_with_id(THIRD_DRAFT_ID);
        different_wallet.user_wallet = Pubkey::new_unique().to_string();
        let market = MockMarketSource::new(vec![
            snapshot(FIRST_MARKET_SLOT, 165, 210),
            snapshot(FIRST_MARKET_SLOT + 99, 999, 888),
            snapshot(FIRST_MARKET_SLOT + 199, 777, 666),
        ]);
        let clock = StepClock::new(FINALIZE_STARTED_AT_MS, CLOCK_STEP_MS);

        let first_response = finalize_intent_json(
            &first,
            Some(&market),
            &sidecar,
            &watch_rules,
            &funding_intents,
            &clock,
        )
        .await
        .expect("first finalize");
        let retry_response = finalize_intent_json(
            &first,
            Some(&market),
            &sidecar,
            &watch_rules,
            &funding_intents,
            &clock,
        )
        .await
        .expect("same-draft retry is a normal response");
        assert_eq!(retry_response["status"], "already_finalized_or_missing");
        assert_eq!(
            market.calls(),
            1,
            "same-draft rejection must happen before the market read"
        );

        let retyped_response = finalize_intent_json(
            &second,
            Some(&market),
            &sidecar,
            &watch_rules,
            &funding_intents,
            &clock,
        )
        .await
        .expect("fresh draft with identical semantics");
        assert_eq!(market.calls(), 2);
        assert_eq!(retyped_response["status"], "funding_required");
        assert_eq!(retyped_response["intent_id"], first_response["intent_id"]);
        assert_eq!(retyped_response["rule_hash"], first_response["rule_hash"]);
        assert_eq!(retyped_response["reused_existing_intent"], true);
        assert_eq!(
            retyped_response["funding"]["user_wallet"], TEST_USER_WALLET,
            "collision recovery must expose the authoritative row"
        );
        assert_eq!(
            retyped_response["signing"]["request_wallet_matches_persisted"],
            true
        );

        let rule = watch_rules
            .get(&expected_rule().rule_id)
            .await
            .expect("watch-rule lookup")
            .expect("persisted rule");
        assert_eq!(
            rule.rule.created_at_slot, FIRST_MARKET_SLOT,
            "collision recovery must use the persisted rule, not the fresh live-slot rule"
        );
        let funding = funding_intents
            .get(EXPECTED_INTENT_ID)
            .await
            .expect("funding lookup")
            .expect("persisted funding row");
        assert_eq!(funding.native_onchain_apr_bps_at_creation, 165);
        assert_eq!(funding.save_display_apy_bps_at_creation, 210);
        assert_eq!(
            retyped_response["created_at_ms"], funding.created_at_ms,
            "collision recovery must not invent a fresh funding deadline"
        );
        assert_eq!(
            retyped_response["expires_at_ms"], funding.expires_at_ms,
            "collision recovery must expose the authoritative deadline"
        );
        assert_eq!(
            retyped_response["funding"]["expires_at_ms"], funding.expires_at_ms,
            "collision funding instructions must use the persisted deadline"
        );
        assert_eq!(
            signing_page_payload(&retyped_response)["funding"]["expires_at_ms"],
            funding.expires_at_ms,
            "collision signing URLs must carry the persisted deadline verbatim"
        );

        let wallet_conflict = finalize_intent_json(
            &different_wallet,
            Some(&market),
            &sidecar,
            &watch_rules,
            &funding_intents,
            &clock,
        )
        .await
        .expect("different-wallet collision is a normal response");
        assert_eq!(market.calls(), 3);
        assert_eq!(wallet_conflict["status"], "existing_intent_conflict");
        assert_eq!(wallet_conflict["persisted_status"], "funding_required");
        assert!(
            wallet_conflict.get("funding").is_none(),
            "wallet collision must never return actionable funding instructions"
        );

        close_test_store(db, watch_rules, funding_intents, sidecar).await;
    }

    #[tokio::test]
    async fn existing_intent_at_exact_deadline_is_not_actionable() {
        let (_file, db, watch_rules, funding_intents, sidecar) = test_store().await;
        let first = params_with_id(FIRST_DRAFT_ID);
        let second = params_with_id(SECOND_DRAFT_ID);
        let market = MockMarketSource::new(vec![
            snapshot(FIRST_MARKET_SLOT, 165, 210),
            snapshot(FIRST_MARKET_SLOT + 99, 999, 888),
        ]);

        let first_clock = StepClock::new(FINALIZE_STARTED_AT_MS, CLOCK_STEP_MS);
        let first_response = finalize_intent_json(
            &first,
            Some(&market),
            &sidecar,
            &watch_rules,
            &funding_intents,
            &first_clock,
        )
        .await
        .expect("first finalize");
        let authoritative_expiry = funding_intents
            .get(EXPECTED_INTENT_ID)
            .await
            .expect("funding lookup")
            .expect("persisted funding row")
            .expires_at_ms;

        // Hold every clock read exactly on the persisted endpoint. The final
        // actionability check must treat now == expires_at_ms as expired.
        let expired_clock = StepClock::new(authoritative_expiry, 0);
        let expired_response = finalize_intent_json(
            &second,
            Some(&market),
            &sidecar,
            &watch_rules,
            &funding_intents,
            &expired_clock,
        )
        .await
        .expect("expired collision is a normal response");

        assert_eq!(first_response["funding_actionable"], true);
        assert_eq!(expired_response["status"], "funding_required");
        assert_eq!(expired_response["funding_actionable"], false);
        assert_eq!(expired_response["expires_at_ms"], authoritative_expiry);
        assert!(
            expired_response.get("funding").is_none(),
            "expired existing intent must not expose signing instructions"
        );
        assert!(
            expired_response.get("signing").is_none(),
            "an expired intent must not invite a signature"
        );
        assert!(
            expired_response.get("signing_page_url").is_none(),
            "a non-actionable intent must not expose a signing-page handoff"
        );

        close_test_store(db, watch_rules, funding_intents, sidecar).await;
    }

    #[tokio::test]
    async fn deterministic_id_collision_with_wrong_rule_shape_fails_closed() {
        let (_file, db, watch_rules, funding_intents, sidecar) = test_store().await;
        let params = params_with_id(FIRST_DRAFT_ID);
        let mut conflicting_rule = expected_rule();
        conflicting_rule.slippage_bps = 1;
        watch_rules
            .insert(&conflicting_rule)
            .await
            .expect("seed conflicting rule through the public repository");
        let market = MockMarketSource::new(vec![snapshot(FIRST_MARKET_SLOT, 165, 210)]);
        let clock = StepClock::new(FINALIZE_STARTED_AT_MS, CLOCK_STEP_MS);

        let response = finalize_intent_json(
            &params,
            Some(&market),
            &sidecar,
            &watch_rules,
            &funding_intents,
            &clock,
        )
        .await
        .expect("rule collision is a normal response");

        assert_eq!(response["status"], "existing_rule_conflict");
        assert!(
            response.get("funding").is_none(),
            "conflicting rule must never produce funding instructions"
        );
        assert!(funding_intents
            .get(EXPECTED_INTENT_ID)
            .await
            .expect("funding lookup")
            .is_none());

        close_test_store(db, watch_rules, funding_intents, sidecar).await;
    }

    #[test]
    fn watch_rule_expiry_slot_saturates_at_u64_max() {
        let proposal = valid_params();
        let (draft, _) = validate_and_hash_draft(&proposal).expect("valid proposal must hash");
        let rule = build_watch_rule(&draft, u64::MAX - 100).expect("approved draft must map to v2");

        assert_eq!(rule.created_at_slot, u64::MAX - 100);
        assert_eq!(rule.expires_at_slot, u64::MAX);
        assert_eq!(hex_lower(&rule.rule_id), EXPECTED_INTENT_ID);
    }
}
